- name: Download the Application Content
  ansible.builtin.uri:
    url: https://github.com/ChaitanyaChandra/leads/archive/main.zip
    method: GET
    headers:
      Authorization: "Bearer {{ github_token }}"
    dest: /tmp/main.zip

- name: Download and UnZip the Application Content
  ansible.builtin.unarchive:
    src: /tmp/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy App Content
  ansible.builtin.copy:
    src: /tmp/leads-main/
    dest: /home/{{USER}}/{{COMPONENT}}/
    remote_src: yes
  become_user: "{{USER}}"

- name: Install packages based on package.json.
  shell: npm install
  args:
    chdir: "/home/{{USER}}/{{COMPONENT}}"
  become_user: "{{USER}}"